### ISSUE TITLE
NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)

### ISSUE THREAD

**Issue by DenysFrasinich** [dragos/dragos-vscode-scala#45]
Hello!
I have latest version of yours extention from vscode marketplace(v0.1.4) and this sbt-ensime version:
```
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.12")
```
Language server starts but after pressing Ctrl+Space it shows empty pop-up with "Loading.." 
I have this stacktrace in pc.stdout.log in root folder of my project:
```
Jun 12, 2017 11:49:28 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=3,486MB (heap=3,486MB direct=3,486MB os=15,680MB), assuming maximum direct memory size equals to maximum JVM heap size
Jun 12, 2017 11:49:28 PM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=15680m option when you start the JVM.
Exception in thread "pool-5-thread-3" java.lang.NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)V
	at org.github.dragos.vscode.EnsimeLanguageServer.org$github$dragos$vscode$EnsimeLanguageServer$$toSourceFileInfo(EnsimeLanguageServer.scala:329)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$6.apply(EnsimeLanguageServer.scala:202)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$6.apply(EnsimeLanguageServer.scala:200)
	at scala.Option.map(Option.scala:146)
	at org.github.dragos.vscode.EnsimeLanguageServer.gotoDefinitionRequest(EnsimeLanguageServer.scala:200)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:23)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:16)
	at langserver.core.Connection$$anonfun$handleCommand$1.apply(Connection.scala:161)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-5-thread-5" java.lang.NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)V
	at org.github.dragos.vscode.EnsimeLanguageServer.org$github$dragos$vscode$EnsimeLanguageServer$$toSourceFileInfo(EnsimeLanguageServer.scala:329)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$5.apply(EnsimeLanguageServer.scala:180)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$5.apply(EnsimeLanguageServer.scala:178)
	at scala.Option.map(Option.scala:146)
	at org.github.dragos.vscode.EnsimeLanguageServer.completionRequest(EnsimeLanguageServer.scala:178)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:21)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:16)
	at langserver.core.Connection$$anonfun$handleCommand$1.apply(Connection.scala:161)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-5-thread-1" java.lang.NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)V
	at org.github.dragos.vscode.EnsimeLanguageServer.org$github$dragos$vscode$EnsimeLanguageServer$$toSourceFileInfo(EnsimeLanguageServer.scala:329)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$5.apply(EnsimeLanguageServer.scala:180)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$5.apply(EnsimeLanguageServer.scala:178)
	at scala.Option.map(Option.scala:146)
	at org.github.dragos.vscode.EnsimeLanguageServer.completionRequest(EnsimeLanguageServer.scala:178)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:21)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:16)
	at langserver.core.Connection$$anonfun$handleCommand$1.apply(Connection.scala:161)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-5-thread-2" java.lang.NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)V
	at org.github.dragos.vscode.EnsimeLanguageServer.org$github$dragos$vscode$EnsimeLanguageServer$$toSourceFileInfo(EnsimeLanguageServer.scala:329)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$7.apply(EnsimeLanguageServer.scala:255)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$7.apply(EnsimeLanguageServer.scala:253)
	at scala.Option.map(Option.scala:146)
	at org.github.dragos.vscode.EnsimeLanguageServer.hoverRequest(EnsimeLanguageServer.scala:253)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:25)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:16)
	at langserver.core.Connection$$anonfun$handleCommand$1.apply(Connection.scala:161)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-5-thread-4" java.lang.NoSuchMethodError: org.ensime.api.SourceFileInfo.<init>(Lorg/ensime/api/EnsimeFile;Lscala/Option;Lscala/Option;)V
	at org.github.dragos.vscode.EnsimeLanguageServer.org$github$dragos$vscode$EnsimeLanguageServer$$toSourceFileInfo(EnsimeLanguageServer.scala:329)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$7.apply(EnsimeLanguageServer.scala:255)
	at org.github.dragos.vscode.EnsimeLanguageServer$$anonfun$7.apply(EnsimeLanguageServer.scala:253)
	at scala.Option.map(Option.scala:146)
	at org.github.dragos.vscode.EnsimeLanguageServer.hoverRequest(EnsimeLanguageServer.scala:253)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:25)
	at langserver.core.LanguageServer$$anonfun$1.apply(LanguageServer.scala:16)
	at langserver.core.Connection$$anonfun$handleCommand$1.apply(Connection.scala:161)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Here is the content of ensime-langserver.log 
```
[2017-06-12 23:48:57,713] INFO org.github.dragos.vscode.Main$ - Starting server in /home/myusername/devstudio/workspace/scala/tmp/test
[2017-06-12 23:48:57,713] INFO org.github.dragos.vscode.Main$ - Starting server in /home/myusername/devstudio/workspace/scala/tmp/test
[2017-06-12 23:48:57,725] INFO org.github.dragos.vscode.Main$ - Classpath: /home/myusername/.vscode-oss/extensions/dragos.scala-lsp-0.1.4/coursier
[2017-06-12 23:48:57,725] INFO org.github.dragos.vscode.Main$ - Classpath: /home/myusername/.vscode-oss/extensions/dragos.scala-lsp-0.1.4/coursier
[2017-06-12 23:48:58,120] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[2017-06-12 23:48:58,531] INFO org.github.dragos.vscode.EnsimeLanguageServer - Initialized with 5221, /home/myusername/devstudio/workspace/scala/tmp/test, ClientCapabilities()
[2017-06-12 23:48:58,531] INFO org.github.dragos.vscode.EnsimeLanguageServer - Initialized with 5221, /home/myusername/devstudio/workspace/scala/tmp/test, ClientCapabilities()
[2017-06-12 23:48:58,666] ERROR langserver.core.Connection - No notification type exists with method=initialized
[2017-06-12 23:48:58,666] ERROR langserver.core.Connection - No notification type exists with method=initialized
[2017-06-12 23:49:27,001] WARN org.ensime.config.EnsimeConfigProtocol$ - /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/classes does not exist, creating
[2017-06-12 23:49:27,023] WARN org.ensime.config.EnsimeConfigProtocol$ - /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/test-classes does not exist, creating
[2017-06-12 23:49:27,052] INFO org.github.dragos.vscode.EnsimeLanguageServer - Using configuration: EnsimeConfig(/home/myusername/devstudio/workspace/scala/tmp/test,/home/myusername/devstudio/workspace/scala/tmp/test/.ensime_cache,/usr/lib/jvm/java-8-openjdk-amd64,test,2.12.2,List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(/usr/lib/jvm/java-8-openjdk-amd64/src.zip),List(EnsimeProject(EnsimeProjectId(root,compile),List(),Set(/home/myusername/devstudio/workspace/scala/tmp/test/src/main/java, /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/src_managed/main, /home/myusername/devstudio/workspace/scala/tmp/test/src/main/scala-2.12, /home/myusername/devstudio/workspace/scala/tmp/test/src/main/scala),Set(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/classes),List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.2-sources.jar),List(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/hello_2.12-0.1.0-SNAPSHOT-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.12.2-javadoc.jar)), EnsimeProject(EnsimeProjectId(root,test),List(),Set(/home/myusername/devstudio/workspace/scala/tmp/test/src/test/java, /home/myusername/devstudio/workspace/scala/tmp/test/src/test/scala-2.12, /home/myusername/devstudio/workspace/scala/tmp/test/src/test/scala, /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/src_managed/test),Set(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/test-classes),List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/bundles/scala-parser-combinators_2.12-1.0.4.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.2.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.5.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/bundles/scalactic_2.12-3.0.1.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/bundles/scalatest_2.12-3.0.1.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.2-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/srcs/scala-parser-combinators_2.12-1.0.4-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.12.2-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/srcs/scala-xml_2.12-1.0.5-sources.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/srcs/scalactic_2.12-3.0.1-sources.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/srcs/scalatest_2.12-3.0.1-sources.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.12.2-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/docs/scala-parser-combinators_2.12-1.0.4-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.12.2-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/docs/scala-xml_2.12-1.0.5-javadoc.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/docs/scalactic_2.12-3.0.1-javadoc.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/docs/scalatest_2.12-3.0.1-javadoc.jar))),List(/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar))
[2017-06-12 23:49:27,052] INFO org.github.dragos.vscode.EnsimeLanguageServer - Using configuration: EnsimeConfig(/home/myusername/devstudio/workspace/scala/tmp/test,/home/myusername/devstudio/workspace/scala/tmp/test/.ensime_cache,/usr/lib/jvm/java-8-openjdk-amd64,test,2.12.2,List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(/usr/lib/jvm/java-8-openjdk-amd64/src.zip),List(EnsimeProject(EnsimeProjectId(root,compile),List(),Set(/home/myusername/devstudio/workspace/scala/tmp/test/src/main/java, /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/src_managed/main, /home/myusername/devstudio/workspace/scala/tmp/test/src/main/scala-2.12, /home/myusername/devstudio/workspace/scala/tmp/test/src/main/scala),Set(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/classes),List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.2-sources.jar),List(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/hello_2.12-0.1.0-SNAPSHOT-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.12.2-javadoc.jar)), EnsimeProject(EnsimeProjectId(root,test),List(),Set(/home/myusername/devstudio/workspace/scala/tmp/test/src/test/java, /home/myusername/devstudio/workspace/scala/tmp/test/src/test/scala-2.12, /home/myusername/devstudio/workspace/scala/tmp/test/src/test/scala, /home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/src_managed/test),Set(/home/myusername/devstudio/workspace/scala/tmp/test/target/scala-2.12/test-classes),List(-feature, -deprecation, -Xlint, -Ywarn-dead-code, -Ywarn-numeric-widen, -Xfuture, -Ywarn-unused-import, -Ymacro-expand:discard),List(),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/bundles/scala-parser-combinators_2.12-1.0.4.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.2.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.5.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/bundles/scalactic_2.12-3.0.1.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/bundles/scalatest_2.12-3.0.1.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.2-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/srcs/scala-parser-combinators_2.12-1.0.4-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.12.2-sources.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/srcs/scala-xml_2.12-1.0.5-sources.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/srcs/scalactic_2.12-3.0.1-sources.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/srcs/scalatest_2.12-3.0.1-sources.jar),List(/home/myusername/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.12.2-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.12/docs/scala-parser-combinators_2.12-1.0.4-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.12.2-javadoc.jar, /home/myusername/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/docs/scala-xml_2.12-1.0.5-javadoc.jar, /home/myusername/.ivy2/cache/org.scalactic/scalactic_2.12/docs/scalactic_2.12-3.0.1-javadoc.jar, /home/myusername/.ivy2/cache/org.scalatest/scalatest_2.12/docs/scalatest_2.12-3.0.1-javadoc.jar))),List(/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar))
[2017-06-12 23:49:27,056] INFO org.github.dragos.vscode.ensime.EnsimeActor - Starting problematic actor now
[2017-06-12 23:49:27,056] INFO org.github.dragos.vscode.ensime.EnsimeActor - Starting problematic actor now
[2017-06-12 23:49:27,058] INFO org.github.dragos.vscode.ensime.EnsimeActor - Created: Actor[akka://ENSIME/user/server/ensimeProject#465310670]
[2017-06-12 23:49:27,058] INFO org.github.dragos.vscode.ensime.EnsimeActor - Created: Actor[akka://ENSIME/user/server/ensimeProject#465310670]
[2017-06-12 23:49:27,068] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding ConnectionInfoReq
[2017-06-12 23:49:27,068] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding ConnectionInfoReq
[2017-06-12 23:49:27,083] INFO org.apache.commons.vfs2.impl.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
[2017-06-12 23:49:28,306] INFO org.ensime.indexer.graph.GraphService - creating the graph database...
[2017-06-12 23:49:57,251] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got goto definition request at (7, 15).
[2017-06-12 23:49:57,251] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got goto definition request at (7, 15).
[2017-06-12 23:49:59,774] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-12 23:49:59,774] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-12 23:50:06,642] INFO org.ensime.indexer.graph.GraphService - ... created the graph database
[2017-06-12 23:50:06,694] INFO akka.actor.DeadLetterActorRef - Message [org.ensime.api.ConnectionInfo] from Actor[akka://ENSIME/user/server/ensimeProject/project#-97422125] to Actor[akka://ENSIME/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2017-06-12 23:50:08,618] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)
[2017-06-12 23:50:08,618] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.ensime.EnsimeProjectServer - Analyzer is ready!
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.ensime.EnsimeProjectServer - Analyzer is ready!
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.ensime.EnsimeProjectServer - Full typecheck complete event
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.ensime.EnsimeProjectServer - Full typecheck complete event
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.EnsimeLanguageServer - Received 0 notes.
[2017-06-12 23:50:08,648] INFO org.github.dragos.vscode.EnsimeLanguageServer - Received 0 notes.
[2017-06-12 23:50:57,092] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding IndexerReadyEvent
[2017-06-12 23:50:57,092] DEBUG org.github.dragos.vscode.ensime.EnsimeProjectServer - Forwarding IndexerReadyEvent
[2017-06-13 00:01:42,434] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got hover request at (3, 6).
[2017-06-13 00:01:42,434] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got hover request at (3, 6).
[2017-06-13 00:01:42,446] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:01:42,446] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:01:42,920] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got hover request at (2, 10).
[2017-06-13 00:01:42,920] INFO org.github.dragos.vscode.EnsimeLanguageServer - Got hover request at (2, 10).
[2017-06-13 00:01:45,167] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:01:45,167] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:01:46,756] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:01:46,756] ERROR langserver.core.Connection - No notification type exists with method=$/cancelRequest
[2017-06-13 00:08:34,722] INFO langserver.core.MessageReader - End of stream, terminating thread
[2017-06-13 00:08:34,722] INFO langserver.core.MessageReader - End of stream, terminating thread
[2017-06-13 00:08:34,722] INFO org.github.dragos.vscode.EnsimeLanguageServer - Shutdown request
[2017-06-13 00:08:34,722] INFO org.github.dragos.vscode.EnsimeLanguageServer - Shutdown request

```

**Comment by dragos** [comment]
Thanks for reporting! Looks like Ensime changed some APIs

**Comment by dragos** [comment]
I'll cut a new release, hopfully the Ensime people will provide a stable release number I can use.

**Comment by fommil** [comment]
yup, will do

**Comment by dragos** [comment]
Please upgrade to 0.1.6, should be fixed. Thanks @fommil  for the 2-M2 release!
