### ISSUE TITLE
loadConfig error at windows 10 (0.2.0)

### ISSUE THREAD

**Issue by gotoeveryone** [dragos/dragos-vscode-scala#60]
Hi, 

When installing 0.2.0 and opening the Scala project, the following error is output to `pc.stdout.log`.
Perhaps because on Windows separator is `\\`, it is not correctly parsed with json-rpc.

OS: Windows 10
VSCode: 1.16.1

```sh
com.typesafe.config.ConfigException$Parse: String: 1: Expecting a value but got wrong token: 'U' (backslash followed by 'U', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) (if you intended 'U' (backslash followed by 'U', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:473)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:1000)
	at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:1010)
	at org.github.dragos.vscode.EnsimeLanguageServer.loadConfig(EnsimeLanguageServer.scala:88)
	at org.github.dragos.vscode.EnsimeLanguageServer.$anonfun$initializeEnsime$1(EnsimeLanguageServer.scala:96)
	at scala.util.Try$.apply(Try.scala:209)
	at org.github.dragos.vscode.EnsimeLanguageServer.initializeEnsime(EnsimeLanguageServer.scala:95)
	at org.github.dragos.vscode.EnsimeLanguageServer.initialize(EnsimeLanguageServer.scala:76)
	at langserver.core.LanguageServer.$anonfun$connection$1(LanguageServer.scala:19)
	at langserver.core.Connection.$anonfun$handleCommand$1(Connection.scala:163)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Hypnoes** [comment]
Yes, it's occurred to me too.

**Comment by Hypnoes** [comment]
Thanks for fix this, but when would it be release?

**Comment by dragos** [comment]
Sorry it took a bit longer, but the release is finally out. Please install 0.2.1 to get around this issue.

**Comment by gotoeveryone** [comment]
@dragos 
Confirmed fix it. Great thanks!!
