### ISSUE TITLE
Crashes on OS X with FileSystemNotFoundException

### ISSUE THREAD

**Issue by Lakret** [dragos/dragos-vscode-scala#87]
For some reason, langserver doesn't work on my MBP. I have an encrypted filesystem (APFS), maybe that's the problem? 

From `ensime-langserver.log`:

```
[2018-06-06 11:29:25,198] ERROR org.github.dragos.vscode.ensime.EnsimeActor - Actor crashed:
java.nio.file.FileSystemNotFoundException: Provider "untitled" not installed
	at java.nio.file.Paths.get(Paths.java:147)
	at org.github.dragos.vscode.EnsimeLanguageServer.$anonfun$publishDiagnostics$2(EnsimeLanguageServer.scala:187)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.immutable.Stream.foreach(Stream.scala:531)
	at org.github.dragos.vscode.EnsimeLanguageServer.publishDiagnostics(EnsimeLanguageServer.scala:186)
	at org.github.dragos.vscode.ensime.EnsimeProjectServer$$anonfun$receive$1.applyOrElse(EnsimeProjectServer.scala:54)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at org.github.dragos.vscode.ensime.EnsimeProjectServer.aroundReceive(EnsimeProjectServer.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by dragos** [comment]
Sounds like a very good guess. I don't have an encrypted FS so I can't help, unfortunately.
