### ISSUE TITLE
Unresolved dependency issue.

### ISSUE THREAD

**Issue by shoorlyne** [dragos/dragos-vscode-scala#91]
I am seeing the following error when trying to run `sbt publishLocal`:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.triplequote#sbt-hydra;0.9.11: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.triplequote:sbt-hydra:0.9.11 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.triplequote:sbt-hydra:0.9.11 (scalaVersion=2.10, sbtVersion=0.13) (/dragos-vscode-scala/project/hydra.sbt#L5-6)
[warn] 		  +- default:dragos-vscode-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.triplequote#sbt-hydra;0.9.11: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.triplequote#sbt-hydra;0.9.11: not found
```

How can I get around this?

Thanks!

**Comment by dragos** [comment]
Ah, I checked-in the [Hydra](www.triplequote.com) sbt-plugin. To get around this, please delete or comment out the contents of `project/hydra.sbt`

**Comment by shoorlyne** [comment]
Thanks! Now I got past that point.

I am now seeing a new issue, when running `vsce package`:

```
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   156  100   156    0     0    280      0 --:--:-- --:--:-- --:--:--   280
100   167  100   167    0     0    144      0  0:00:01  0:00:01 --:--:--   144
100 11832  100 11832    0     0   9185      0  0:00:01  0:00:01 --:--:--  213k
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scala-lsp@0.2.3 vscode:prepublish: `curl -L -o coursier https://github.com/alexarchambault/coursier/raw/991b60ddbcb7d781c17a463f7af980f2dd888d4b/coursier && tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the scala-lsp@0.2.3 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-19T10_31_51_391Z-debug.log
```

The detailed log looks like:

```
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle scala-lsp@0.2.3~prevscode:prepublish: scala-lsp@0.2.3
6 info lifecycle scala-lsp@0.2.3~vscode:prepublish: scala-lsp@0.2.3
7 verbose lifecycle scala-lsp@0.2.3~vscode:prepublish: unsafe-perm in lifecycle true
8 verbose lifecycle scala-lsp@0.2.3~vscode:prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/dragos-vscode-scala/scala/node_modules/.bin:/root/scala-2.12.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle scala-lsp@0.2.3~vscode:prepublish: CWD: /dragos-vscode-scala/scala
10 silly lifecycle scala-lsp@0.2.3~vscode:prepublish: Args: [ '-c',
10 silly lifecycle   'curl -L -o coursier https://github.com/alexarchambault/coursier/raw/991b60ddbcb7d781c17a463f7af980f2dd888d4b/coursier && tsc -p ./' ]
11 silly lifecycle scala-lsp@0.2.3~vscode:prepublish: Returned: code: 2  signal: null
12 info lifecycle scala-lsp@0.2.3~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: scala-lsp@0.2.3 vscode:prepublish: `curl -L -o coursier https://github.com/alexarchambault/coursier/raw/991b60ddbcb7d781c17a463f7af980f2dd888d4b/coursier && tsc -p ./`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid scala-lsp@0.2.3
15 verbose cwd /dragos-vscode-scala/scala
16 verbose Linux 4.17.17-x86_64-linode116
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error scala-lsp@0.2.3 vscode:prepublish: `curl -L -o coursier https://github.com/alexarchambault/coursier/raw/991b60ddbcb7d781c17a463f7af980f2dd888d4b/coursier && tsc -p ./`
22 error Exit status 2
23 error Failed at the scala-lsp@0.2.3 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by dragos** [comment]
Sorry for all the trouble, indeed there was a problem with the build. I just pushed a commit that fixes is on my machine. Please let me know if you can build now.

**Comment by shoorlyne** [comment]
Build looks good now. Thanks!
